# Generated by Django 5.2.12 on 2026-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
    ]
