# Generated by Django 5.2.12 on 2026-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contents_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL содержания'),
        ),
    ]
