# Generated by Django 5.2.12 on 2026-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0003_alter_book_contents_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
