# Generated by Django 5.2.12 on 2026-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0004_alter_book_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rightholder',
        ),
        migrations.AddField(
            model_name='book',
            name='rightholder',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='sonicgrid.rightholder', verbose_name='Правообладатель'),
        ),
    ]
