# Generated by Django 5.2.12 on 2026-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0005_remove_book_rightholder_book_rightholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='sonicgrid.genre', verbose_name='Жанры'),
        ),
    ]
