# Generated by Django 5.2.12 on 2026-03-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0006_remove_book_genres_book_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='full_name_rodit',
            new_name='full_rodit',
        ),
        migrations.AlterField(
            model_name='bookcontributor',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('corrector', 'Corrector'), ('illustrator', 'Illustrator'), ('translator', 'Translator'), ('publisher', 'Publisher'), ('reader', 'Reader')], max_length=100, verbose_name='Вклад в книгу'),
        ),
    ]
