# Generated by Django 5.2.12 on 2026-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0007_rename_full_name_rodit_contributor_full_rodit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='ID'),
        ),
    ]
