# Generated by Django 5.2.12 on 2026-03-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonicgrid', '0008_contributor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor_uuid',
            new_name='uuid',
        ),
    ]
